// Client/src/app/layout/layout.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from './header/header.component';
import { MainComponent } from './main/main.component';
import { FooterComponent } from './footer/footer.component';

@Component({
  selector: 'layout',
  standalone: true,
  imports: [HeaderComponent,MainComponent,FooterComponent],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent {

}

<header></header>
<main></main>
<footer></footer>

// client-react/src/layout/layout.tsx
import React from "react";
import Header from "./header/Header";
import Main from "./main/Main";
import Footer from "./footer/Footer";
import "./layout.css";
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="layout-container">
        <Header />
        <Main children={children} />
        <Footer />
      </div>
    </>
  );
}
